version: '3.7'
services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - "mongodata:/d/mongo/data/db"
    networks:
      my_compose_network:
        ipv4_address: 172.88.88.2
  rest_to_kafka:
    image: rest-to-kafka:latest
    depends_on:
      - kafka
    container_name: rest-to-kafka
    ports:
      - "9990:9990"
    networks:
      my_compose_network:
        ipv4_address: 172.88.88.3
    environment:
      KAFKA_HOST: 172.88.88.5
      KAFKA_PORT: 9092
      KAFKA_TOPIC: demo
      PORT: :9990
  kafka_to_mongo:
    image: kafka-to-mongo:latest
    container_name: kafka-to-mongo
    networks:
      my_compose_network:
        ipv4_address: 172.88.88.6
    environment:
      KAFKA_HOST_PORT: 172.88.88.5:9092
      KAFKA_TOPIC: demo
      MONGODB_HOST_PORT: 172.88.88.2:27017
      DATABASE: "db"
      DB_USER_NAME: ""
      DB_PASSWORD: ""
      COLLECTION: "jobs"
  kafka:
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    networks:
      my_compose_network:
        ipv4_address: 172.88.88.5
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 172.88.88.5
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      my_compose_network:
        ipv4_address: 172.88.88.4
volumes:
   mongodata:

networks:
  my_compose_network:
    name: my_compose_network
    ipam:
      config:
        - subnet: 172.88.88.0/16
      